{% set name = "pyspartn" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyspartn-{{ version }}.tar.gz
  sha256: 69a0e60f5d16d3a49cd853749754e4ed49b8a4a6a8fa2f5ab8eb6ba824984188

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - cryptography >=42.0.0
test:
  imports:
    - pyspartn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pyspartn
  description: Python library for parsing SPARTN GNSS protocol messages.
  summary: SPARTN protocol parser
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyspartn
  dev_url: https://github.com/semuconsulting/pyspartn

extra:
  recipe-maintainers:
    - semuadmin
