{% set name = "pyspartn" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspartn-{{ version }}.tar.gz
  sha256: 22b2e63a778229176f5716799a05e1660f8ab38766b32fe8b0fc461bbe13ba71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - cryptography >=39.0.2

test:
  imports:
    - pyspartn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pyspartn
  description: Python library for parsing SPARTN GNSS protocol messages.
  summary: SPARTN protocol parser
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyspartn
  dev_url: https://github.com/semuconsulting/pyspartn

extra:
  recipe-maintainers:
    - semuadmin
